### PR TITLE
merge inn platform changes

### PR DESCRIPTION
**Pull request by andrerom**
merge in changes from platform as a first step towards doing a 1.1 release.

*update: as agreed below this repo is as part of the merge adjusted to be closer to upstream.*

### CODE REVIEW

**Comment by andrerom** [comment]
@SylvainGuittard / @bdunogier POV on if this repo should be in close sync with ezplatform, or use stable packages as is the case?

**Comment by bdunogier** [comment]
Both are valid. The merge of what happens in ezsystems/ezplatform@master will have to be manual anyway.

**Comment by SylvainGuittard** [comment]
Thanks @andrerom for the PR!
I think ezplatform-demo should be as close as possible to ezplatform. 

+1

**Comment by andrerom** [comment]
ok, will update this next week when 1.1.0 is out.

**Comment by bdunogier** [comment]
It is out, you can go ahead. Note that there is a commit in the unstable
version that must be reverted (the one that sets the aliases).

**Comment by andrerom** [comment]
PR updated, as agreed I instead merge in changes from master, and then releases can be done as second step.

**Comment by bdunogier** [comment]
> branch name is miss leading

I knew about miss france or miss norway, not miss leading :angel: 

+1

**Comment by andrerom** [comment]
> I knew about miss france or miss norway, not miss leading :angel:

she won over miss losing :ok_woman:

**Comment by SylvainGuittard** [comment]
Thanks @andrerom

**Pull request merged**
