### PR TITLE
EZP-25228: Added Favicon for eZ Platform

### PR DESCRIPTION
**Pull request by jheba**

### CODE REVIEW

**Comment by clash82** [comment]
+1

**Comment by bdunogier** [comment]
No `#` prefix on the issue number. You can also drop the "implemented", what about:

`EZP-25228: added favicon` ?

**Comment by andrerom** [comment]
+1 

@clash82 Could you or others in the team check if markup + paths here is correct? If so this is ready for merge.

**Comment by jheba** [comment]
@bdunogier oh... Sorry, I didn't notice the format has changed.
IIRC that was required format in the past: ```Implemented|Fixed #issue_number: issue_summary```?

**Comment by clash82** [comment]
@andrerom I can confirm, everything is correct here (tested).

**Comment by jheba** [comment]
ref. http://share.ez.no/learn/ez-publish/how-to-contribute-to-ez-publish-using-git/(page)/5#eztoc515031_10_13

**Comment by bdunogier** [comment]
> @bdunogier oh... Sorry, I didn't notice the format has changed.
> IIRC that was required format in the past: Implemented|Fixed #issue_number: issue_summary

We don't use a `#` because it exists nowhere on JIRA, that's all.
About "Implemented", it's mostly because only the first 50 characters of a commit message are displayed in logs, and it is a long word :-)

**Comment by andrerom** [comment]
Thanks for the rebase @jheba, merging :tada: :)

**Comment by SylvainGuittard** [comment]
@jheba Thanks for the PR

**Pull request merged**
