### PR TITLE
Fixed preview of the blog_post content draft

### PR DESCRIPTION
**Pull request by clash82**
Should be included with https://github.com/ezsystems/ezplatform-demo/commit/91a2c13a78bc2eb11159015dc7c246e3845e6842

### CODE REVIEW

**Comment by clash82** [comment]
ping @SylvainGuittard @damianz5

**Comment by SylvainGuittard** [comment]
+1

**Comment by damianz5** [comment]
+1

**Comment by andrerom** [comment]
(side: in retrospective this should have been applied on 1.5 branch and up)

**Comment by clash82** [comment]
> (side: in retrospective this should have been applied on 1.5 branch and up)

Yes, that's true :(
@andrerom should I cherry pick this commit on 1.5 branch or is there a more proper way?

**Comment by andrerom** [comment]
you can do that, but make sure to merge 1.5 into master so they stay in sync.

**Comment by clash82** [comment]
@andrerom I was wrong. This commit should belong to master only as it fixes issue with blog_post preview but after implementing QueryTypes (added in 1.6).

This one here https://github.com/ezsystems/ezplatform-demo/commit/91a2c13a78bc2eb11159015dc7c246e3845e6842 fixes same issue but before QueryTypes. So partially it's related (fixes same template) but should stay on master at this moment.

Description was misleading, sorry for that.

**Pull request merged**
