### PR TITLE
Run the CLI installer, but only if it hasn't been run

### PR DESCRIPTION
**Pull request by Crell**
Open question: Is the lock file approach sufficient?

### CODE REVIEW

**Comment by andrerom** [comment]
I'll say it depends on the use case, for the one here I guess it is good enough. What else did you have in mind?

**Comment by Crell** [comment]
The alternative would be to push essentially the same logic further back, with a dedicated run-once deploy hook.  That would require considerably deeper changes to Platform, however, and we're not sure on the timeline for that.

The master branch check is arguably unnecessary.  That can be removed easily if you'd prefer.

The main question here is whether the lock file is a sufficiently robust way to ensure the installer isn't run multiple times.

It's probably wise to also enhance the install script itself to self check to see if it's already installed, and then not do so if it is.  There could be a --force option to override that if desired.  Just an extra check to make sure we don't inadvertently overwrite an already-running install when deploying code changes.

I also wasn't able to fully test the site after it's installed since the admin shell seems to be missing, or else I am not sure where to login.  Is it not at `/shell`?

**Comment by andrerom** [comment]
ok

> The master branch check is arguably unnecessary. That can be removed easily if you'd prefer.

I don't know what that is for, I'm assuming this is not git branches we talk about here :) 

> It's probably wise to also enhance the install script itself to self check to see if it's already installed, and then not do so if it is. There could be a --force option to override that if desired. Just an extra check to make sure we don't inadvertently overwrite an already-running install when deploying code changes.

makes sense, it would then typically prompt user, so we'll make sure it just stops on non interactive use then unless -y or --force or similar is provided.

> I also wasn't able to fully test the site after it's installed since the admin shell seems to be missing, or else I am not sure where to login. Is it not at /shell?

it's at `/ez` since last fall, did you see any referances to it on `/shell` on existing doc?

**Comment by Crell** [comment]
It is git branches, actually. :smile: Every git branch is/can be an environment of the same name. The code as written says the installer will try to run iff we're on the "master" (production) environment (which an initial deploy will always be) and the lock file doesn't already exist.  The need for that first check is debatable, since the initial deployment will always be on master anyway.

Found the admin now, thanks. H had just been googling, and apparently the current docs don't have very good google juice yet. I kept finding stuff from a decade ago, when apparently it was much harder and therefore more talked about.

**Comment by Crell** [comment]
@andrerom Is there anything else you need here or is this ready to merge?

**Comment by andrerom** [comment]
No this is good, merging.

What's the next issue from your side? On our side I'm not sure if you have heard but there is a potential project on platform.sh in germany and they are trying to enable caching to use Fastly, which I guess is what we should enable here as well, if this is clustered we need to use a shared http cache*(, as well as stash cache)*.

**Pull request merged**
