### PR TITLE
EZP-26037: As an user, I want to be able to register

### PR DESCRIPTION
**Pull request by clash82**
https://jira.ez.no/browse/EZP-26037

Registration form + user menu:
screen shot 2016-09-05 at 15 11 03

Confirmation page:
screen shot 2016-09-05 at 15 11 34

### CODE REVIEW

**Comment by clash82** [comment]
review please @SylvainGuittard @inakijv @damianz5 @kamilmusial

**Comment by damianz5** [comment]
+1

**Comment by SylvainGuittard** [comment]
+1

**Comment by kamilmusial** [comment]
+1

**Pull request merged**
