### PR TITLE
Updated vhost configuration for nginx (added rewrite rule for assets directory)

### PR DESCRIPTION
**Pull request by clash82**

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Comment by andrerom** [comment]
@bdunogier should we cherry pick this to upstream? And how does this fit with what you had in mind for tutorial?

**Comment by andrerom** [comment]
@clash82 your comment on the issue said "fix this in nginx _to_", are there modifications on apache vhost here that we should be aware of and cherry pick to upstream?

**Comment by clash82** [comment]
Exactly, sorry I didn't respond so quickly :)

**Comment by bdunogier** [comment]
If everybody thinks it's a good convention, then let's go upstream. Like salmons :fish

**Comment by andrerom** [comment]
:fishing_pole_and_fish: https://github.com/ezsystems/ezplatform/pull/94

**Comment by clash82** [comment]
I'm just wondering if it's really needed in platform? changes were maybe especially because of the demo requirements - it's only one of the possible approaches.

**Comment by andrerom** [comment]
reasoning is that we need something like this for tutorial as well to show where you'd put project assets, input on alternatives are welcome. But we would like a convention that we use in demo and tutorials.

**Comment by clash82** [comment]
ok, it's more clear to me now (didn't thought about the tutorial...)
Thank you.

**Pull request merged**
