### PR TITLE
Fix EZP-25829: EzBehatExtension should be activated in Platform demo

### PR DESCRIPTION
**Pull request by glye**
> Implements https://jira.ez.no/browse/EZP-25829
> Status: Ready for review

Ref: https://github.com/ezsystems/ezplatform/commit/f82fa586ddc53a33ef6c699e05c1233346767b5b
This was done in Platform, should be done in Platform-demo too.

Ping @bdunogier @andrerom

### CODE REVIEW

**Comment by bdunogier** [comment]
Not that useful without behat being executed on this repo, but still good.

+1

**Comment by bdunogier** [comment]
Merged to 1.3, please merge to master @glye.

**Comment by glye** [comment]
@bdunogier Done, hope this is halal: https://github.com/ezsystems/ezplatform-demo/commits/master

**Comment by bdunogier** [comment]
As long as you said a prayer and were headed towards the mecca, you should be fine :-)

(yes it is)

**Pull request merged**
