### PR TITLE
EZP-26429: Updated search index

### PR DESCRIPTION
**Pull request by damianz5**
https://jira.ez.no/browse/EZP-26429

### CODE REVIEW

**Comment by andrerom** [comment]
The diff is to large, did you dump it in another way perhaps?

**Comment by damianz5** [comment]
No, before the dump there was almost no entries in tables `ezsearch_object_word_link` (before ~36 rows, after 3236 rows) and `ezsearch_word` (before 24 rows, after 1290 rows). I can put those two tables to separate file `app_data_search.sql` and modify `AppBundle/Installer/AppInstaller.php`

**Comment by damianz5** [comment]
The sql changes of this PR could be displayed by [link](https://patch-diff.githubusercontent.com/raw/ezsystems/ezplatform-demo/pull/45.diff)

**Comment by andrerom** [comment]
@damianz5 / @clash82 / @SylvainGuittard @lserwatka the fixes for search engine has been merged, so we can attempt to re index and get these fixes in for the release.


ref: https://github.com/ezsystems/ezpublish-kernel/commit/ba75da6fd3329fa70a34d66e435a96899cef1d7d

**Comment by lserwatka** [comment]
@damianz5 is looking into it.
ping @andrerom

**Comment by damianz5** [comment]
PR updated, [changes](https://patch-diff.githubusercontent.com/raw/ezsystems/ezplatform-demo/pull/45.diff)

**Comment by SylvainGuittard** [comment]
Can we merge this PR?

**Comment by clash82** [comment]
> Can we merge this PR?

+1

**Comment by damianz5** [comment]
Travis build error is not related to this PR

**Comment by andrerom** [comment]
> Travis build error is not related to this PR

confirmed, REST functional tests are broken on master here to /cc @bdunogier @nicolas-bastien 
merging :)

**Pull request merged**
