### PR TITLE
EZP-25837: inaccessible/missing fonts on eZ Platform 2016.04

### PR DESCRIPTION
**Pull request by damianz5**
https://jira.ez.no/browse/EZP-25837

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
+1

**Comment by andrerom** [comment]
-1


1, If it has been `font` before we shoudl consider to add it as `s?` so both works
2. this should go to upsream *(ezplatform)* and merged down here

**Comment by damianz5** [comment]
@andrerom i consider it, but [composer.json](https://github.com/ezsystems/ezplatform-demo/blob/master/composer.json#L48) use `components/font-awesome`
and their convention in css files is `fonts/`
https://github.com/components/font-awesome/blob/master/css/font-awesome.css#L9

**Comment by andrerom** [comment]
Thats not waht I'm saying, I'm saying we need to have consistent rewrite rules across projects, and I'm also saying we need to think BC when we change it in case people are using font folder now.

**Comment by andrerom** [comment]
+1 but please reopen this on `ezplatform` repo against 1.3 branch and I'll handle merging it here.

**Comment by damianz5** [comment]
related: https://github.com/ezsystems/ezplatform/pull/115

**Pull request closed without merging**
