### PR TITLE
Fixed invalid pagelayout variable in contact form post submit template

### PR DESCRIPTION
**Pull request by bdunogier**
> JIRA: http://jira.ez.no/browse/EZP-25737

Uses `app.configResolver()` to read the setting. It is the ugliest method, but also the most limited scope wise. A solution will have to be found either in a higher layer in the demo, or in platform itself (discussed in the issue).

### CODE REVIEW

**Comment by andrerom** [comment]
Is this then also something we need to fix in all pagelayouts?

**Comment by bdunogier** [comment]
What do you mean by "in all pagelayouts" André ?

Content view templates are not affected, as the pagelayout is set by the view request handler. The contact form is not a view, and therefore must be fixed differently. 

The current idea for a more sustainable fix, in platform itself, is to expose the pagelayout setting in the `ezpublish` twig gobal we have.

**Comment by andrerom** [comment]
I probably looked to fast, was thinking this was relevant to the changes we did across all installs for 2016.04.

**Comment by bdunogier** [comment]
Not sure which changes this is exactly, but it is related to the introduction of the `ezpublish.pagelayout` setting in ezplatform. When this feature was applied to the demo, I overlooked that the contact form template was not a content view, and therefore did not have access to that variable.

**Comment by andrerom** [comment]
ok

**Comment by SylvainGuittard** [comment]
thanks @bdunogier

**Pull request merged**
